src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[Vich\Uploadable]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]

    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[Vich\UploadableField(mapping: 'formationimg', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'formations')]
    #[ORM\JoinColumn(nullable: false)]
    private $User;

    #[ORM\OneToMany(mappedBy: 'Formation', targetEntity: Section::class, orphanRemoval: true)]
    private $sections;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): self
    {
        if (!$this->sections->contains($section)) {
            $this->sections[] = $section;
            $section->setFormation($this);
        }

        return $this;
    }

    public function removeSection(Section $section): self
    {
        if ($this->sections->removeElement($section)) {
            // set the owning side to null (unless already changed)
            if ($section->getFormation() === $this) {
                $section->setFormation(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/FormationsController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Entity\Lesson;
use App\Entity\Section;
use Doctrine\ORM\Query;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class FormationsController extends AbstractController
{
    public function __construct(private ManagerRegistry $doctrine) {}

    #[Route('/formations', name: 'app_formations')]
    public function index(): Response
    {
        $formations = $this->doctrine->getRepository(Formation::class)->findAll();
        return $this->render('formations/index.html.twig', [
            'formations' => $formations,
    ]);
    }

    #[Route('/formations/consulter-{formation}-{section}-{id}', name: 'app_formations_lesson')]
    public function seeLesson($formation, $id): Response
    {
        $formation = $this->doctrine->getRepository(Formation::class)->findOneById($formation);
        $sections  = $this->doctrine->getRepository(Section::class)->findAll();
        $lessons = $this->doctrine->getRepository(Lesson::class)->findOneById($id);
        return $this->render('formations/lesson.html.twig', [
            'lessons' => $lessons,
            'formation' => $formation,
            'sections' => $sections
        ]);
    }

    #[Route('/formations/consulter-{id}', name: 'app_formations_see')]
    public function see($id): Response
    {
        $formation = $this->doctrine->getRepository(Formation::class)->findOneById($id);
        $sections  = $this->doctrine->getRepository(Section::class)->findAll();
        $lessons = $this->doctrine->getRepository(Lesson::class)->findAll();
        return $this->render('formations/formation.html.twig', [
            'formation' => $formation,
            'sections' => $sections,
            'lessons' => $lessons
        ]);
    }
}

templates/formations/formation.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ formation.title }}{% endblock %}
{% block footerbottom %}
    {% block content %}
        <div class="formationcontainer text-center">
        {% block sidebar %}
            {% include "./formations/sidebar.html.twig" %}
        {% endblock %}
            <h1>{{ formation.title }} par {{ formation.user.firstname }} {{ formation.user.lastname }}</h1>
            {{ formation.description }}
            <hr>
            <h2>Bien commencer sa formation</h2>
            <p class="lesson_content">
            Nulla mattis ipsum sed consequat auctor. Sed ante leo, viverra non justo eget, scelerisque pulvinar enim. Mauris vel gravida justo. Aenean commodo enim ex. Sed pretium vulputate neque, in condimentum nisl eleifend ac. Etiam eu massa eu felis tempor fermentum. Ut dignissim id magna nec molestie. Proin efficitur, diam non finibus sollicitudin, tortor tellus rutrum erat, et vestibulum neque nunc in tortor. Sed sodales orci bibendum enim tristique bibendum. Sed bibendum at lectus sed aliquet. Suspendisse vel lorem vel mi venenatis porta vel in lacus. Donec ut nisi blandit, accumsan ligula et, vestibulum quam. Ut id mauris in neque euismod tincidunt aliquet vel nulla. Quisque lacinia consectetur felis, in cursus odio vehicula vel.
            </p>
        </div>
    {% endblock %}
{% endblock %}

templates/formations/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Formations{% endblock %}
{% block content %}
    <div class="blockcontainer text-center">
        <h1>Nos formations</h1>
        <br>
        <div class="search">
            <form>
                <label for="live_search">Rechercher une formation :</label>
                <input type="text" id="live_search" size="30" class="form-control" placeholder="Rechercher une formation" />
            </form>
        </div>
        <br>
            <div class="container px-5 mb-3">
                <div class="row">
                    {% for formation in formations %}
                            <div class="card me-lg-4 mb-3">
                                <img class="card-img-top" src="{{ vich_uploader_asset(formation, 'imageFile') }}" alt="{{ formation.imageName }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ formation.title }}</h5>
                                    <p class="card-text">{{ formation.description }}</p><br>
                                    <div class="bottom-line-card">
                                        <a class="small btn btn-success custom-btn rounded-pill mt-2" href="{{path('app_formations_see', {'id' : formation.id })}}" role="button">voir</a>
                                    </div>
                                </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
    </div>
{% endblock %}

templates/formations/lesson.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ lessons.title }}{% endblock %}
{% block footerbottom %}
    {% block content %}
        <div class="formationcontainer text-center">
            {% block sidebar %}
                {% include "./formations/sidebar.html.twig" %}
            {% endblock %}
            <h1>{{ lessons.title }}</h1>
            <hr>
            <iframe width="560" height="315" src="{{ lessons.video }}" title="YouTube video" allow="accelerometer; autoplay" allowfullscreen></iframe>
            <br>
               <p class="lesson_content">{{ lessons.content|striptags }}</p>
        </div>
{% endblock %}
{% endblock %}

templates/formations/sidebar.html.twig
<!-- Sidear for lesson pages -->

<nav class="flex-shrink-0flex-shrink-0 p-3 bg-white sidenav h-100">
    <button class="btn btn-success" id="sidenav-btn" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarCollapse" aria-expanded="false" aria-controls="collapseOne">
        Sommaire
    </button>
    <div class="list-unstyled ps-0 ul-custom navbar-collapse collapse show" id="sidebarCollapse" aria-expanded="true">
        <li class="mb-1">
            {% for sections in formation.sections %}
                <ul class="list-unstyled align-items-center rounded fw-normal">
                    <li>{{ sections.name }}</li>
                </ul>
                <div>
                    {% for lessons in sections.lessons %}
                        <ul class="list-unstyled fw-normal pb-1 small">
                            <li><a href="{{ path('app_formations_lesson',  {'formation':formation.id, 'section': sections.id, 'id':lessons.id}) }}" class="link-dark rounded">{{ lessons.title }}</a></li>
                        </ul>
                    {% endfor %}
                </div>
            {% endfor %}
        </li>
        <li class="border-top my-3"></li>
        <li class="mb-1">
            <ul class="list-unstyled fw-normal pb-1 small">
                <li><a href="{{path('app_formations')}}" class="link-dark rounded">retour à la liste des formations</a></li>
            </ul>
        </li>
    </div>
</nav>